generated_at = "2026-07-17T22:27:11Z"
generated_by = "kagami auto-discover --write-cache"
source_mtime_iso = "2026-07-17T22:26:11Z"
source_sha = "1daf584"

[[scopes]]
discovered_via = "swift-package-ast"
language = "swift"
module_patterns = ["ShellKitTests"]
name = "ShellKitTests"
package_path = "/Users/jeoffrey/.shikki/workspaces/obyw-one/projects/ShellKit"
source_paths = ["Tests/ShellKitTests/"]
test_command = ["swift", "test", "--filter", "ShellKitTests"]
test_file_patterns = []
test_target_name = "ShellKitTests"
type_patterns = []
